name: CI/CD Pipeline

# This workflow runs when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest  # Adjust this if you're using a different testing framework

  deploy:
    runs-on: ubuntu-latest
    needs: test  # This ensures the deploy job only runs after tests pass

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Render
      run: |
        source venv/bin/activate
        pip install render-cli
        render deploy --service <your-service-id> --api-key ${{ secrets.RENDER_API_KEY }}
